updated to use python based simulation study

diff --git a/crownet/simulations/cmp_vadere_sumo/run_study b/crownet/simulations/cmp_vadere_sumo/run_study
--- a/crownet/simulations/cmp_vadere_sumo/run_study
+++ b/crownet/simulations/cmp_vadere_sumo/run_study
@@ -1,42 +1,30 @@
 #!/bin/bash
 
-ALL_CONFIGS="sumoSimple vadereSimple sumoBottleneck vadereBottleneck"
+# simulation studies to be run
+declare -a STUDIES=("simple_study.py")
 
-start_container () {
-  if docker ps | grep -q $1; then 
-        echo "Container for $1 is already available."
-    else
-        echo "Starting container for $1..."
-        $1 & disown
-        sleep 5
-    fi
-}
+ENV_ACTIVATE="out/crownet_user/bin/activate"
 
-if [[ $# -lt 1 ]]; then
-    echo "Illegal number of parameters: Please specify the configuration to be used." >&2
-    echo ""
-    echo "Usage: $0 [configuration] [max. threads (opt.)]"
-    echo "       Use \"all\" as configuration name to run all configurations (except the base configs)."
-    echo ""
-    echo "Valid configurations: $ALL_CONFIGS"
-    exit 2
+if [[ -z "${CROWNET_HOME}" ]]; then
+    echo "Environment variable CROWNET_HOME is not set - please set it to the folder in which you cloned the CrowNet repository."
+    exit 1
 fi
 
-start_container sumo
-start_container vadere
-
-NRTHREADS=$(getconf _NPROCESSORS_ONLN)
-
-if [[ $# -eq 2 ]]; then
-    NRTHREADS=$2
+if [[ ! -f "${CROWNET_HOME}/${ENV_ACTIVATE}" ]]; then
+    echo "Missing environment activation script: $CROWNET_HOME/$ENV_ACTIVATE"
+    echo "Please run \"omnetpp exec make analysis-all\" in $CROWNET_HOME to create the environments."
+    exit 1
 fi
 
-echo "INFO: Using $NRTHREADS parallel threads for simulation study."
+source $CROWNET_HOME/$ENV_ACTIVATE
 
-if [ $1 == "all" ]; then
-    for cfg in $ALL_CONFIGS; do
-        omnetpp exec opp_runall -j$NRTHREADS ../../src/run_crownet -n .:../../src -u Cmdenv -c $cfg
-    done
-else
-    omnetpp exec opp_runall -j$NRTHREADS ../../src/run_crownet -n .:../../src -u Cmdenv -c $1
-fi
+pushd .
+cd ./study
+for study in "${STUDIES[@]}"
+do
+    python3 $study
+done
+popd
+
+# TODO: Analysis should better be performed as part of the postprocessing
+python3 ./analysis.py
