[Analysis uq] add tests to CI

diff --git a/scripts/run_simulations_Diss_Mayr b/scripts/run_simulations_Diss_Mayr
--- a/scripts/run_simulations_Diss_Mayr
+++ b/scripts/run_simulations_Diss_Mayr
@@ -18,14 +18,16 @@ wait_symbol () {
 	echo " "
 }
 
-source ${CROWNET_HOME}/setup -i
 
 if [ -z "${OPP_EXTERN_DATA_MNT}" ]; then
       echo 'Variabel 'OPP_EXTERN_DATA_MNT' not set. Example > export OPP_EXTERN_DATA_MNT="/mnt/data1TB/:/mnt/data1TB:rw"'
       exit -1
 fi
 
+
 echo "##################################### prepare output directory  #######################################"
+
+simulation_storage="/mnt/data1TB/storage"
 
 output_folder=${CROWNET_HOME}/output_diss_cm
 echo "Write output of simulations to the directory ${output_folder}/"
@@ -77,37 +79,49 @@ source ${CROWNET_HOME}/out/crownet_user/bin/activate
 
 echo "################################### information dissemination uq study #################################"
 
+set +e && docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && set -e 
+
 simulation_dir="${CROWNET_HOME}/analysis/uq/simulation_studies/forward_propagation_and_sensitvity_analysis"
-result_dir="${simulation_dir}/PolynomialChaos_results"
 
 echo "Run the uq study: ${simulation_dir}" | tee -a $LOG_FILE
 echo "Simulation started: `date`"| tee -a $LOG_FILE
 
 cd ${simulation_dir}
-python3 step2_run_simulations.py & pid=$! && wait_symbol $pid
+python3 run_simple_detour_sa_fp.py "${simulation_storage}/information_diss_time" 2 2000 6 >> $LOG_FILE & pid=$! && wait_symbol $pid
 
 echo "Simulation finished: `date`"| tee -a $LOG_FILE
 echo "Copy simulation results from ${result_dir} to ${output_folder}/direct_communication" | tee -a $LOG_FILE           
-cp -r ${result_dir} ${output_folder}/direct_communication/
 
-exit 0
 
+echo "################################### information dissemination shadowing #################################"
+
+set +e && docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && set -e 
+
+simulation_dir="${CROWNET_HOME}/analysis/uq/simulation_studies/forward_propagation"
+
+echo "Run the uq study: ${simulation_dir}" | tee -a $LOG_FILE
+echo "Simulation started: `date`"| tee -a $LOG_FILE
+
+cd ${simulation_dir}
+python3 run_simple_detour_shadowing.py "${simulation_storage}/shadowing" 120 120 8 >> $LOG_FILE & pid=$! && wait_symbol $pid
 
 
 echo "####################################### compare guiding strategies ########################################"
 
 
+set +e && docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && set -e
 
 simulation_dir="${CROWNET_HOME}/analysis/uq/simulation_studies/guiding_crowds_forward_propagation"
 echo "Run the simulation study: compare guiding strategies in the simulation directory: ${simulation_dir}" | tee -a $LOG_FILE
 echo "Simulation started: `date`"| tee -a $LOG_FILE
 
 cd ${simulation_dir}
-python3 run_simulations.py & pid=$! && wait_symbol $pid
+python3 run_simulations.py "${simulation_storage}/guiding_strategies" 41 8 10 >> $LOG_FILE & pid=$! && wait_symbol $pid
+python3 analyze_sim_results.py "${simulation_storage}/guiding_strategies" >> $LOG_FILE & pid=$! && wait_symbol $pid
 
-#TODO analyze results
 
 echo "#################################### sim : realistic scenario ########################################"
+set +e && docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && set -e
 
 simulation_dir="${CROWNET_HOME}/crownet/simulations/mucFreiheit_route_choice_app"
 echo "Run the simulation of the realistic scenario in the simulation directory: ${simulation_dir}" | tee -a $LOG_FILE
@@ -118,18 +132,23 @@ label="diss_cm"
 result_dir="${simulation_dir}/results/${config}_${label}"
 
 cd ${simulation_dir}
-python3 run_script.py vadere-opp-control --write-container-log --create-vadere-container --override-host-config --experiment-label "${label}" --vadere-tag 496ff02c --control-tag 496ff02c --omnet-tag 6.0.1 --with-control control.py --ctrl.controller-type MinimalDensity --opp.-c "${config}" --qoi number_of_peds.txt path_choice.txt densities_mapped.txt packet_loss_info_diss.csv packet_loss_heat_map.csv heat_map_diss_time.csv info_diss_time.csv simsec_sec_ratio.csv docker_stats.csv --log-docker-stats >> $LOG_FILE & pid=$!
-wait_symbol $pid
+python3 run_script.py vadere-opp-control --write-container-log --create-vadere-container --override-host-config --experiment-label "${label}" --vadere-tag 496ff02c --control-tag 496ff02c --omnet-tag 6.0.1 --with-control control.py --ctrl.controller-type MinimalDensity --opp.-c "${config}" --qoi number_of_peds.txt path_choice.txt densities_mapped.txt packet_loss_info_diss.csv packet_loss_heat_map.csv heat_map_diss_time.csv info_diss_time.csv simsec_sec_ratio.csv docker_stats.csv --log-docker-stats >> $LOG_FILE & pid=$! && wait_symbol $pid
 
 echo "Simulation finished : `date`"| tee -a $LOG_FILE
 echo "Copy simulation results to ${output_folder}/realistic_scenario" | tee -a $LOG_FILE           
 cp -r ${result_dir} ${output_folder}/realistic_scenario/
 
 
-exit 0
+echo "Check the simulation output" | tee -a $LOG_FILE
+realistic_scenario_hash=$(find find $CROWNET_HOME/output_diss_cm/realistic_scenario -type f \( -name '*.txt' -o -name 'postvis.traj' -o -name 'info_diss_time.csv' \)  -exec md5sum {} \; | md5sum | cut -b 1-32) 
+realistic_scenario_hash_exp="7ca66d74b8b541205cd7ca52b695d59e"
 
 
-
+if [ "$realistic_scenario_hash" == "$realistic_scenario_hash_exp" ]; then
+    echo "Realistic scenario: Simulation output has been re-produced successfully. Fingerprint match." | tee -a $LOG_FILE
+else
+    echo "ERROR Realistic scenario: Simulation output has not been re-produced successfully. Fingerprint do not match." | tee -a $LOG_FILE
+fi
 
 
 
